mkdir "$1"
cd "$1"
mkdir ".vscode"
cd ".vscode"
touch "settings.json"
echo "{" >> "settings.json"
echo "    \"deno.enable\": true," >> "settings.json"
echo "    \"deno.unstable\": true" >> "settings.json"
echo "}" >> "settings.json"
cd ".."
touch "polyfill.ts"
touch "spec.md"
echo "# $1" >> "spec.md"
touch "demonstration.ts"
